builds:
  # GOOS list to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are darwin and linux.
  goos:
    - freebsd
    - windows
    - darwin

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386, amd64 and arm64.
  goarch:
    - amd64
    - arm
    - arm64
